### Register a new user
POST {{host}}/register
Content-Type: application/json

{
  "userName": "newuser",
  "password": "newpassword"
}

### Login request
POST {{host}}/login
Content-Type: application/x-www-form-urlencoded

username=newuser
&password=newpassword

### Check for current user
GET {{host}}/current-user

### Logout request
POST {{host}}/logout

### Access blocked ressource (user)
GET {{host}}/greeting-user

### Access blocked ressource (admin)
GET {{host}}/greeting-admin

### Public endpoint
GET {{host}}/greeting