name: Deploy Angular App as static page on dokku

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: main
          git_remote_url: 'ssh://dokku@168.119.171.224/hack-the-room'
          git_push_flags: '--force'
          ssh_private_key: ${{ secrets.SSH_KEY_PRIVATE }}
